### ISSUE TITLE
Can't find variable: _

### ISSUE THREAD

**Issue by vmmatos** [BhavanPatel/react-native-simple-encryption#1]
Hi,
When I debug my android app project gave me an error on line 5, in your xorEncrypt meanning "Can't find variable: _"
How to solve this issue?

Thank you.

**Comment by BhavanPatel** [comment]
@vmmatos Thank you for let me know.
@vmmatos  Please check node_modules is there package `lodash` ? 
if not do `npm install lodash`
and try to run your project if still you have error please let me know.

**Comment by vmmatos** [comment]
ok, I made the installation of the lodash package, but still have the same issue, do not need to declare the variable _ somewhere?

Thanks.

**Comment by BhavanPatel** [comment]
fixed pls uninstall 
`npm uninstall react-native-simple-encryption --save` 
and install 
`npm install react-native-simple-encryption --save`

**Comment by HVHMobileDeveloper** [comment]
> Hi,
> When I debug my android app project gave me an error on line 5, in your xorEncryt meanning "Can't find variable: _"
> How to solve this issue?
> 
> Thank you.

the best way to solve?
