### ISSUE TITLE
Find the secrect key from the encoded screen

### ISSUE THREAD

**Issue by mithunadhikari40** [BhavanPatel/react-native-simple-encryption#3]
How can I find the secret key entered at the time of encryption from the generated encrypted message?
I know it can be achieved reversing the encrypt method, but how do I do that?

**Comment by BhavanPatel** [comment]
You need to use same secret key for decryption. If you are using node as a backend then see this code for backend  [Enc Dec for Node](https://github.com/BhavanPatel/react-native-node-enc-dec/tree/master/Node).
Thanks.
