### ISSUE TITLE
Why two functions?

### ISSUE THREAD

**Issue by samdoj** [BhavanPatel/react-native-simple-encryption#4]
XOR works in both directions.  Doesn't it make more sense to have just one function called crypto that takes either clear text or encrypted text and just XORs it?

**Comment by jacksolutions** [comment]
Good suggestion, yes offcourse it can be done like that, i will amend it and push the latest code.

thank you for your interest

**Comment by BhavanPatel** [comment]
Thank you for reporting issue. I will look into it and release next version as soon as possible. :)
Sorry for late response.
